version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/bocket/"
